import scrapy


class ClinicLocationItem(scrapy.Item):
    type = scrapy.Field()
    name = scrapy.Field()
    address = scrapy.Field()
    address1 = scrapy.Field()
    address2 = scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    region = scrapy.Field()
    postalCode = scrapy.Field()
    country = scrapy.Field()
    countryCode = scrapy.Field()
    phone = scrapy.Field()
    fax = scrapy.Field()
    email = scrapy.Field()
    website = scrapy.Field()
    hours = scrapy.Field()
    services = scrapy.Field()
    sourceType = scrapy.Field()
    sourceTag = scrapy.Field()
    sourceUrl = scrapy.Field()
    evidenceUrl = scrapy.Field()
    evidenceNote = scrapy.Field()
    internalStatus = scrapy.Field()
    crawlRunKey = scrapy.Field()
    lat = scrapy.Field()
    lng = scrapy.Field()
